### ISSUE TITLE
Device ID matching issue

### ISSUE THREAD

**Issue by jetaylor80** [bpmurray/node-red-contrib-ds18b20-sensor#2]
When supplying a device id in the msg.topic field my device is never found.  I found the issue was that the match is case sensitive. My device ID was 000003BB163E. I fixed the issue by modifying the findDevice function as follows:

// Return the deviceList entry, given a device ID
      this.findDevice = function(deviceList, devId) {
         devId = devId.toUpperCase();
         for (var iX=0; iX<deviceList.length; iX++) {
**//Modified code**
            if (devId === deviceList[iX].file.substr(3)**.toUpperCase()** ||
                devId === deviceList[iX].id) {
               return deviceList[iX];
            }
         }
         // If it's not in the normalised form
         var tmpDev = devId.substr(13,2) + devId.substr(11,2) +
                      devId.substr(9,2)  + devId.substr(7,2)  +
                      devId.substr(5,2)  + devId.substr(3,2);
         for (var iX=0; iX<deviceList.length; iX++) {
            if (devId === deviceList[iX].file.substr(3) ||
                devId === deviceList[iX].id) {
               return deviceList[iX];
            }
         }
         
         return null;
      }

**Comment by bpmurray** [comment]
Thanks for finding that - I've updated and published to npmjs.org
