### ISSUE TITLE
Does not find my sensors

### ISSUE THREAD

**Issue by Toshibass** [bpmurray/node-red-contrib-ds18b20-sensor#3]
I wondered if you have any idea whats going on here 

I activate the DS18B20 node with a blank string and the result is ...

22/03/2017, 08:45:55node: da6e5911.571938
msg : error
"Error: ENOENT: no such file or directory, open '/sys/bus/w1/devices/not found./w1_slave'"
22/03/2017, 08:45:55node: e001cf74.3eef2

But if I send    ls /sys/bus/w1/devices   in a exec node I can see my sensors 

msg.payload : string[280]
string[280]
26-0000018f0b3c
26-0000018f35dd
28-000004816b68
28-000004de52e9
28-000004f98638
28-00000515fd8f
28-000005164c50
29-00000012534b
29-0000001335bd
3a-0000001726c8
w1_bus_master1
w1_bus_master2
w1_bus_master3
w1_bus_master4
w1_bus_master5
w1_bus_master6
w1_bus_master7
w1_bus_master8

I have a similar setup on a different pi with different DS18B20 sensors and the works perfectly (on that pi I only have DS18B20 sensors connected) So it perhaps because it see's 26-0... first and not 28-0... if so then the following does not appear to work...

_This reads the list of all available sensors using the Dallas One-Wire Protocol, and retrieves the temperature from those sensors that provide a temperature value._

**Comment by bpmurray** [comment]
That's interesting - the root cause of this is indicated by the error message:
```
Error: ENOENT: no such file or directory, open '/sys/bus/w1/devices/not found./w1_slave'`
```
This shows that something is, as the message says "not found". What happens is, simply that it tries to read the list of files from /sys/devices/w1_bus_master but clearly gets a "not found" error and it uses this text to try to access a device called "not found". 

To help me resolve the problem, can you do an ls -l on two folders, please, and put the output in a response below:
```
ls -l /sys/devices/w1*
ls -l /sys/bus/w1/devices
```
I can add something to prevent this error, but the side-effect is that it won't find your devices!

**Comment by Toshibass** [comment]
Thanks for your quick response here as requested is results...
________________________________________________________________________________________________
I did notice all the DS18B20 sensors are on Bus master 8 with the other devices on Bus master 7 when I check my other pi which is working with this node the DS18B20 sensors are on Bus master 1

If I run webiopi I can get the sensor data no problem but the whole idea is to replace webiopi with node-red
________________________________________________________________________________________________

pi@raspberrypi:/ $ ls -l /sys/devices/w1*
/sys/devices/w1_bus_master1:
total 0
lrwxrwxrwx 1 root root    0 Mar 22 11:18 driver -> ../../bus/w1/drivers/w1_master_driver
drwxr-xr-x 2 root root    0 Mar 22 11:18 power
lrwxrwxrwx 1 root root    0 Mar 22 11:18 subsystem -> ../../bus/w1
-rw-r--r-- 1 root root 4096 Mar 22 11:18 uevent
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_add
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_attempts
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_max_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_name
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_pointer
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_pullup
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_remove
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_search
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slaves
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout_us

/sys/devices/w1_bus_master2:
total 0
lrwxrwxrwx 1 root root    0 Mar 22 11:18 driver -> ../../bus/w1/drivers/w1_master_driver
drwxr-xr-x 2 root root    0 Mar 22 11:18 power
lrwxrwxrwx 1 root root    0 Mar 22 11:18 subsystem -> ../../bus/w1
-rw-r--r-- 1 root root 4096 Mar 22 11:18 uevent
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_add
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_attempts
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_max_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_name
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_pointer
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_pullup
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_remove
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_search
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slaves
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout_us

/sys/devices/w1_bus_master3:
total 0
lrwxrwxrwx 1 root root    0 Mar 22 11:18 driver -> ../../bus/w1/drivers/w1_master_driver
drwxr-xr-x 2 root root    0 Mar 22 11:18 power
lrwxrwxrwx 1 root root    0 Mar 22 11:18 subsystem -> ../../bus/w1
-rw-r--r-- 1 root root 4096 Mar 22 11:18 uevent
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_add
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_attempts
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_max_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_name
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_pointer
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_pullup
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_remove
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_search
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slaves
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout_us

/sys/devices/w1_bus_master4:
total 0
lrwxrwxrwx 1 root root    0 Mar 22 11:18 driver -> ../../bus/w1/drivers/w1_master_driver
drwxr-xr-x 2 root root    0 Mar 22 11:18 power
lrwxrwxrwx 1 root root    0 Mar 22 11:18 subsystem -> ../../bus/w1
-rw-r--r-- 1 root root 4096 Mar 22 11:18 uevent
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_add
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_attempts
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_max_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_name
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_pointer
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_pullup
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_remove
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_search
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slaves
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout_us

/sys/devices/w1_bus_master5:
total 0
lrwxrwxrwx 1 root root    0 Mar 22 11:18 driver -> ../../bus/w1/drivers/w1_master_driver
drwxr-xr-x 2 root root    0 Mar 22 11:18 power
lrwxrwxrwx 1 root root    0 Mar 22 11:18 subsystem -> ../../bus/w1
-rw-r--r-- 1 root root 4096 Mar 22 11:18 uevent
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_add
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_attempts
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_max_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_name
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_pointer
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_pullup
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_remove
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_search
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slaves
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout_us

/sys/devices/w1_bus_master6:
total 0
lrwxrwxrwx 1 root root    0 Mar 22 11:18 driver -> ../../bus/w1/drivers/w1_master_driver
drwxr-xr-x 2 root root    0 Mar 22 11:18 power
lrwxrwxrwx 1 root root    0 Mar 22 11:18 subsystem -> ../../bus/w1
-rw-r--r-- 1 root root 4096 Mar 22 11:18 uevent
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_add
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_attempts
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_max_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_name
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_pointer
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_pullup
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_remove
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_search
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slaves
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout_us

/sys/devices/w1_bus_master7:
total 0
drwxr-xr-x 3 root root    0 Mar 22 11:18 26-0000018f0b3c
drwxr-xr-x 3 root root    0 Mar 22 11:18 26-0000018f35dd
drwxr-xr-x 3 root root    0 Mar 22 11:18 29-00000012534b
drwxr-xr-x 3 root root    0 Mar 22 11:18 29-0000001335bd
drwxr-xr-x 3 root root    0 Mar 22 11:18 3a-0000001726c8
lrwxrwxrwx 1 root root    0 Mar 22 11:18 driver -> ../../bus/w1/drivers/w1_master_driver
drwxr-xr-x 2 root root    0 Mar 22 11:18 power
lrwxrwxrwx 1 root root    0 Mar 22 11:18 subsystem -> ../../bus/w1
-rw-r--r-- 1 root root 4096 Mar 22 11:18 uevent
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_add
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_attempts
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_max_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_name
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_pointer
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_pullup
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_remove
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_search
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slaves
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout_us

/sys/devices/w1_bus_master8:
total 0
drwxr-xr-x 3 root root    0 Mar 22 11:18 28-000004816b68
drwxr-xr-x 3 root root    0 Mar 22 11:18 28-000004de52e9
drwxr-xr-x 3 root root    0 Mar 22 11:18 28-000004f98638
drwxr-xr-x 3 root root    0 Mar 22 11:18 28-00000515fd8f
drwxr-xr-x 3 root root    0 Mar 22 11:18 28-000005164c50
lrwxrwxrwx 1 root root    0 Mar 22 11:18 driver -> ../../bus/w1/drivers/w1_master_driver
drwxr-xr-x 2 root root    0 Mar 22 11:18 power
lrwxrwxrwx 1 root root    0 Mar 22 11:18 subsystem -> ../../bus/w1
-rw-r--r-- 1 root root 4096 Mar 22 11:18 uevent
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_add
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_attempts
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_max_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_name
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_pointer
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_pullup
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_remove
-rw-rw-r-- 1 root root 4096 Mar 22 11:18 w1_master_search
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slave_count
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_slaves
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout
-r--r--r-- 1 root root 4096 Mar 22 11:18 w1_master_timeout_us


pi@raspberrypi:/ $ ls -l /sys/bus/w1/devices
total 0
lrwxrwxrwx 1 root root 0 Mar 22 11:20 26-0000018f0b3c -> ../../../devices/w1_bus_master7/26-0000018f0b3c
lrwxrwxrwx 1 root root 0 Mar 22 11:20 26-0000018f35dd -> ../../../devices/w1_bus_master7/26-0000018f35dd
lrwxrwxrwx 1 root root 0 Mar 22 11:20 28-000004816b68 -> ../../../devices/w1_bus_master8/28-000004816b68
lrwxrwxrwx 1 root root 0 Mar 22 11:20 28-000004de52e9 -> ../../../devices/w1_bus_master8/28-000004de52e9
lrwxrwxrwx 1 root root 0 Mar 22 11:20 28-000004f98638 -> ../../../devices/w1_bus_master8/28-000004f98638
lrwxrwxrwx 1 root root 0 Mar 22 11:20 28-00000515fd8f -> ../../../devices/w1_bus_master8/28-00000515fd8f
lrwxrwxrwx 1 root root 0 Mar 22 11:20 28-000005164c50 -> ../../../devices/w1_bus_master8/28-000005164c50
lrwxrwxrwx 1 root root 0 Mar 22 11:20 29-00000012534b -> ../../../devices/w1_bus_master7/29-00000012534b
lrwxrwxrwx 1 root root 0 Mar 22 11:20 29-0000001335bd -> ../../../devices/w1_bus_master7/29-0000001335bd
lrwxrwxrwx 1 root root 0 Mar 22 11:20 3a-0000001726c8 -> ../../../devices/w1_bus_master7/3a-0000001726c8
lrwxrwxrwx 1 root root 0 Mar 22 11:20 w1_bus_master1 -> ../../../devices/w1_bus_master1
lrwxrwxrwx 1 root root 0 Mar 22 11:20 w1_bus_master2 -> ../../../devices/w1_bus_master2
lrwxrwxrwx 1 root root 0 Mar 22 11:20 w1_bus_master3 -> ../../../devices/w1_bus_master3
lrwxrwxrwx 1 root root 0 Mar 22 11:20 w1_bus_master4 -> ../../../devices/w1_bus_master4
lrwxrwxrwx 1 root root 0 Mar 22 11:20 w1_bus_master5 -> ../../../devices/w1_bus_master5
lrwxrwxrwx 1 root root 0 Mar 22 11:20 w1_bus_master6 -> ../../../devices/w1_bus_master6
lrwxrwxrwx 1 root root 0 Mar 22 11:20 w1_bus_master7 -> ../../../devices/w1_bus_master7
lrwxrwxrwx 1 root root 0 Mar 22 11:20 w1_bus_master8 -> ../../../devices/w1_bus_master8



NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Raspberry pi 2 b+

**Comment by bpmurray** [comment]
I've updated it with correct behaviour for multiple devices in multiple directories. Please try it now & let me know if it worked (or not!).

**Comment by Toshibass** [comment]
I updated to v1.3.2, stopped & restarted node-red & refreshed web page however I am sorry to report the update has no effect the result is the same as before..

29 Mar 09:21:30 - [error] [rpi-ds18b20:da6e5911.571938] Error: ENOENT: no such file or directory, open '/sys/bus/w1/devices/not found./w1_slave'
29 Mar 09:21:30 - [error] [rpi-ds18b20:28-000004816b68] Error: ENOENT: no such file or directory, open '/sys/bus/w1/devices/not found./w1_slave'

**Comment by bpmurray** [comment]
The only other thing it might be is where it fails for empty directories. I've added a check for that so please try now when you get a chance.

**Comment by Toshibass** [comment]
I updated to v 1.3.3 stopped & restarted node-red & refreshed web page its not working, however the error has changed it appears its failing because it finds a DS2413 1wire i/o chip : 3a-bla bla so I guess its finding bus master 7 first which has a couple of 3a... DS2413 and a couple of 29... DS2408 1wire 8 channel switch devices, before it gets to busmaster 8 that contains the DS18B20 devices.

9 Mar 17:23:07 - [error] [rpi-ds18b20:da6e5911.571938] Error: ENOENT: no such file or directory, open '/sys/bus/w1/devices/3a-0000001726c8/w1_slave'
29 Mar 17:23:07 - [error] [rpi-ds18b20:28-000004816b68] Error: ENOENT: no such file or directory, open '/sys/bus/w1/devices/3a-0000001726c8/w1_slave'

**Comment by bpmurray** [comment]
I think the issue is that it processes those i/o chips expecting them to have the usual w1 files. This latest change verifies that the file exists before trying to access it. I think this should do it - thanks for your patience.

**Comment by Toshibass** [comment]
Its me that should be thanking you for the time and effort you've committed to sort out my pesky problem so thank you very much.
So updating to 1.3.4 solves the problem its finding all my sensors in bus-master 8 and reports the temperatures, fantastic that's how I intend to use it and how my other pi with the sensors in bus master 1 works, its also working as per the readme.md so I can split that message based on the topic (id) of the sensor and it all works fine, its just a bit confusing that the id is not what is usually thought of as the sensor id like 28-000004816b68 but is actually (in this case 686B81040000) but I can live with that so thanks again for your time and effort **SOLVED**

30/03/2017, 07:08:42node: 6bcecba5.3cef94
686B81040000 : msg : Object
object
_msgid: "fa3e5521.0e8168"
topic: "686B81040000"
payload: 12.25
file: "28-000004816b68"
dir: "w1_bus_master8"
family: "28"
