### ISSUE TITLE
"TypeError: Object armv6_1176 has no method 'startsWith'"

### ISSUE THREAD

**Issue by ESPWarren** [bpmurray/node-red-contrib-ds18b20-sensor#4]
Hi,

This is the error message I get when I try to use the  rpi-ds18b20 node.

I think it comes from this line in  ds18b20-node.js

`if ( dirs[iY].startsWith("w1_bus_master") ) {`

If I change that line to detect the start string using use "indexOf", the error disappears, but the node does not give temperatures. The payload is empty.

Independently using a Python script on the same machine gets the temperatures without problem...

On my Raspberry pi, node --version gives:

`v0.10.29`

Thanks

Nick

**Comment by Roaders** [comment]
I have got this as well when upgrading from version `1.2.5` to `1.3.4`.
Reverting to `1.2.5` until this issue is addressed

**Comment by ESPWarren** [comment]
OK Please excuse a noob with Node red - but I seem only to be able to disable the node, not 'uninstall' or 'replace' it....?

**Comment by Roaders** [comment]
You need to remove the relevant directory under `node_modules` or do something along the lines of `npm uninstall -s node-red-contrib-ds18b20-sensor`

**Comment by bpmurray** [comment]
Apologies for the slow response - I was away. That looks strange - my guess is that you're using an old version of node.js. Please run:
`node --version`
I tend to keep stuff up to date so mine shows v7.7.4. Similarly for npm my version shows 3.8.6. You can update your version by following the instructions on https://nodered.org/docs/hardware/raspberrypi - I think the command is "update-nodejs-and-nodered". 

In the meantime, I'll add a protection around this to ensure that it fails gracefully. The update should be available within the hour.

**Comment by Roaders** [comment]
yup, I was on an old version.
