### ISSUE TITLE
No data is read

### ISSUE THREAD

**Issue by Marooned-MB** [bpmurray/node-red-contrib-ds18b20-sensor#6]
Probing from command line works without problems:
```
pi@raspberrypi:~ $ cat /sys/bus/w1/devices/28-000003xxxxxx/w1_slave
4c 01 4b 46 7f ff 04 10 f5 : crc=f5 YES
4c 01 4b 46 7f ff 04 10 f5 t=20750
```
however, this node is returning empty results (topic and payload === ''). Any clues?
RPi model B running Raspbian Stretch

PS, there are 3 other nodes for DS18 available. One requires owfs, but two others work fine with my setup (returns proper temp) however, they ping only one selected DS. Your node is the only one that can return all of them attached to RPi (and I'll have ~10 of them) so I would prefer to use yours once we find out why it's not returning any data.

Thanks

**Comment by bpmurray** [comment]
How did you actually try to get hold of the data? Did you try with an empty topic in the node? That should return readings from all compatible devices.
