### ISSUE TITLE
[Question]: Is this SW part also usable with DS18S20 sensors?

### ISSUE THREAD

**Issue by hasenradball** [bpmurray/node-red-contrib-ds18b20-sensor#7]
Hello,

can I use this node-red SW part also with `DS18S20` sensors?
Or ist it only for `DS18B20 `sensors?

**Comment by bpmurray** [comment]
I haven't tried that particular sensor, but it's still basically the same thing from a software point of view. The Raspberry Pi can read the data from it in the same way as the DS18B20, so it should be fine.

**Comment by hasenradball** [comment]
Heah you are right, the temp calculation is done by the pi. Sorry for the stupid question.
