### ISSUE TITLE
Permanent 1-wire communication after install

### ISSUE THREAD

**Issue by Proamp** [bpmurray/node-red-contrib-ds18b20-sensor#9]
After install this node raspbian starts permanently read sensors every 10 seconds(with and without Node-Red running).

Oscillogram after raspbian start(1-wire pin):

![1_wire_10sec](https://user-images.githubusercontent.com/9385894/60520373-f00bd400-9ced-11e9-9b3f-8730c7568b32.PNG)

How to resolve this problem?

**Comment by bpmurray** [comment]
This is normal. Raspbian has a parameter in  the boot configuration to add support for the Dallas 1-wire protocol - if this is ON it continuously polls for devices. Read https://www.raspberrypi-spy.co.uk/2018/02/enable-1-wire-interface-raspberry-pi/

**Comment by Proamp** [comment]
Thank you for your answer. I already find a solution:

 You can disable the scans from userspace by writing 0 to 
 sys/devices/w1_bus_master1/w1_master_search The default is -1 which means always scan or you can set it to a specific number and it'll decrement it by 1 each time.
